// Generated by uniffi-bindgen-react-native
#include "react-native-sia.h"
#include "generated/rust_lib_files.hpp"

namespace sia {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeRustLibFiles::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}