// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-sia.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "SiaSpec.h"

@interface Sia : NSObject <NativeSiaSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Sia : NSObject <RCTBridgeModule>
#endif

@end