name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate Sia bindings
        run: |
          yarn ubrn:checkout
          yarn ubrn generate jsi turbo-module --native-bindings

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate Sia bindings
        run: |
          yarn ubrn:checkout
          yarn ubrn generate jsi turbo-module --native-bindings

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage

  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate Sia bindings
        run: |
          yarn ubrn:checkout
          yarn ubrn generate jsi turbo-module --native-bindings

      - name: Build package
        run: yarn prepare

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install JDK
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Finalize Android SDK
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Cache Gradle
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('example/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Checkout SDK
        run: yarn ubrn:checkout

      - name: Build Android
        run: yarn ubrn:android

      - name: Build example for Android
        env:
          JAVA_OPTS: '-XX:MaxHeapSize=6g'
        run: |
          yarn build:android

  build-ios:
    runs-on: macos-latest
    env:
      XCODE_VERSION: 16.4
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Select Xcode
        run: sudo xcodes select ${{ env.XCODE_VERSION }}

      - name: Checkout SDK
        run: yarn ubrn:checkout

      - name: Build iOS
        run: yarn ubrn:ios

      - name: Build example for iOS
        run: |
          yarn build:ios
